name: "Build ImmortalWrt Installer ISO"

on:
  workflow_dispatch:
    inputs:
      rt_version:
        description: '选择 ImmortalWrt 版本'
        required: true
        default: '24'
        type: choice
        options:
          - '23'
          - '24'

jobs:
  build-release:
    name: "Build and Release"
    runs-on: "ubuntu-22.04"

    steps:
      - name: "Get Date"
        run: |
          echo "DATESTAMP=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: "Checking out git repository"
        uses: actions/checkout@v2

      - name: Set executable permissions
        run: |
          chmod +x ${{ github.workspace }}/imm.sh
          chmod +x ${{ github.workspace }}/supportFiles/immortalwrt/build.sh

      - name: "Build Image"
        run: |
          ./imm.sh
        env:
          RT_VERSION: ${{ github.event.inputs.rt_version }}

      - name: "Publish"
        run: |
          gh release create ImmortalWrt-Installer-x86_64-ISO \
            --title "ImmortalWrt-Installer-x86_64-ISO" \
            --notes-file ${{ github.workspace }}/supportFiles/immortalwrt/info.md \
            --draft=false \
            output/immortalwrt-installer-x86_64.iso \
          || gh release upload ImmortalWrt-Installer-x86_64-ISO \
            --clobber \
            output/immortalwrt-installer-x86_64.iso
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
